# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Set build number
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install -g @angular/cli
  - npm install -g electron-forge
  - npm install typescript@'>=2.4.2 <2.7.0'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - ng build --aot
  - electron-forge publish --arch=ia32
